# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Tiago Lopes Valença'
description: 'Estudante de Ciência da Computação na C.E.S.A.R. School e poeta nas horas vagas'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
facebook: 'https://www.facebook.com/tiago.valenca.5'
instagram: 'https://www.instagram.com/tiago.valenca/'
github-user: 'https://github.com/tiagovalenca'
#gitlab-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
#blog_url: ''
email: 'tlv.cesar.school'

# Advanced settings
plugins:
  - jekyll-remote-theme
